############ MID Config #############
# optimizer  this json nolog and 32
lr: 0.0001
# nei_attn_mask: True
nei_padding_mask: True
batch_size: 32
train_data_ratio: 1
diffusion_steps: 70  # $$50
# - 500
# - 2000
variance_mode: 'linear'
# 'linear', 'cosine'
val_mode: multistep
# Training Parameters:
#diffnet: Diffuser_ped_inter_geometric_cond_w_history  #
diffnet: Diffuser_ped_inter_geometric_cond_w_obs_w_history
#diffnet: Old_has_obsctcle
#diffnet: new_destination
#diffnet: no_destination
yt_encoder_layers: 3
spatial_emsize: 128
spatial_encoder_head: 4
# spatial_encoder_hidden: 128
spatial_encoder_layers: 2
dropout: 0.3 #0.1 0.3
esti_goal: acce # acce, pos

history_dim: 6 # if esti_goal==acce 6 else 2d
history_emsize: 64
history_lstm: 128
history_lstm_out: 64

ped_encode_dim1: 64
ped_encode_hid1:
- 64
- 64
ped_encode_dim2: 64
ped_encode2_layers: 4

egnn_layers: 3
egnn_hid_dim_obs: 256 # $$64
diff_emb_hid: 64
diff_emb_out: 64

egnn_hid_dim: 256  #$$32

obs_seq_len: 8
pred_seq_len: 20
epochs: -1

# dataset
save_model: True
finetune: True
total_epochs: 160

data_config: configs/data_configs/gc_model.yaml

rebuild_dataset: False
data_dict_path: dataset_built/gc.pkl
model_sd_path: False
finetune_trainmode: multistep # singlestep/multistep
time_decay: 0.9

collision_threshold: 0.5

margin: 0.05
dataset_type: timeindex
finetune_flag: 1
valid_steps: 10
data_dir: processed_data_sf
topk_ped: 6
sight_angle_ped: 90
dist_threshold_ped: 4

sight_angle_obs: 90
dist_threshold_obs: 40
skip_frames: 25
num_history_feature: 8
num_history_velocity: 1
train_mode: multi

  # the path with the directory with XXX.pkl

eval_batch_size: 256
k_eval: 25

seed: 777 #456
eval_every: 1

# Testing
eval_at: 80
eval_mode: False

# Data Parameters:
device: cuda:0
note: None

begin_time: 2025
simulate_time: 675
topk_obs: 10 #10
perception_radius: 5.0
interests_radius: 1.2
grid_size: 0.1
grid_origin: [5.8982, 6.5514] # (world_min_x, world_min_y)
# 7777
num_collision: True
collision_number_weight: 1.0

crowd_dim: 5
crowd_emsize: 64
num_crowd_feature: 8
history_crowd_lstm: 128
history_crowd_lstm_out: 64
crowd_In_egnn: False
has_obstacles: False #000
use_crowd_lstm: False  #333
use_crowd_fusion: False

egnn_layers_obs: 3
use_base: False

topk_brights: 20
sight_angle_brights: 90
dist_threshold_brights: 4
bin: 10


#num_bright: 18
bright_encoder: 5
#bright_out: 64 #64

use_RVO: False    #111
fix: 0.5
use_my_col: True

bg_image: /mnt/d/SPD_2025/data/GC/bg.jpg
cv_save: True

lam: 1.0
max_speed: 2.0
loss: 2

use_json: True #444
json_path: /mnt/d/SPD_2025/configs/gc.json
image_weights_path: /mnt/d/SPD_2025/checkpoints/resnet50-0676ba61.pth
Image_encoder: ResNet
Text_encoder: BERT
text_weights_path: /mnt/d/SPD_2025/checkpoints/bert-base-uncased
text_dim: 768
image_dim: 2048
out_dim: 512
hidden_dim: 256
loss_typr: 2loss
label: gc
use_bright2: False
bright_hidden_dim: 128
out_dim_json: 64
sim: 123
use_obs_sae: True
use_poi_sae: True
ped_num: 1

use_obs_json: True
use_in_json: True
use_env: True
obs_num: 1
bright_hid: 256
bright_out: 64
use_col_focus_loss: False
collision_focus_weight: 0.01
bright_grid: 220 #110
use_ped: True
use_bright: True  #222

use_obs_collision_loss: False